// chat_wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 2 total shaders

textures/chat_wood/chwood_c02
{
    qer_editorimage textures/chat_wood/chwood_c02
	diffusemap textures/chat_wood/chwood_c02
	bumpmap textures/chat_wood/chwood_c02_n
	specularmap textures/chat_wood/chwood_c02_s
	surfaceparm woodsteps
	implicitMap -
	{
	  map textures/chat_wood/chwood_c02
	  VertexColor
	blend blend
	}
}

textures/chat_wood/chwood_c04
{
    qer_editorimage textures/chat_wood/chwood_c04
	diffusemap textures/chat_wood/chwood_c04_n
	specularmap textures/chat_wood/chwood_c04_s
	surfaceparm woodsteps
	implicitMap -
	{
	  map textures/chat_wood/chwood_c04
	  VertexColor
	blend blend
	}
}
